prac/app1/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
app_name = 'app1'
urlpatterns = [
    path('',views.create_user , name='signup'),
    path('login/', views.login_user , name='login'),
    path('home/' , views.home , name='home'),
    path('logout/', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('setting/' , views.setting_view , name='setting'),
    path('ajax/general/',views.general,name='general'),
    path('usersentdata/',views.usersentdata , name='usersentdata'),
    path('passvalidation/',views.passwordvalidation,name='passvalidation'),
    path('addtocart/',views.addtocart,name='addtocart'),
    path('cart/' , views.cartshow,name='cart'),
    path('qntcng/',views.qntcng , name='qntcng'),
    path('bigview/<int:id>/',views.bigpicview ,name='bigview'),
    path('profilepic/', views.imagechange , name='porfilepic'),
]

prac/prac/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('',include('app1.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns+=static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

prac/app1/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import tree


class UserProfile(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE)
    pic = models.ImageField(upload_to = 'images' , default = 'Z:/Django/usercreationform/prac/image/images/default.png')
    company_name = models.CharField(max_length=100 , blank=True )
    valid_seller = models.BooleanField(default=False)
    bio          = models.TextField(max_length=500 , blank=True)

    def __str__(self):
        return self.user.username
    
class ItemListed(models.Model):
    Gender_Choice =[
        ('Male' , 'Male'),
        ('Female' , 'Female'),
        ('Unisex','Unisex'),
    ]
    user = models.ForeignKey(UserProfile , on_delete=models.CASCADE)
    item_name = models.CharField(max_length=50)
    brand = models.CharField(max_length=50 , blank=True)
    pic =  models.ImageField(upload_to='itemImages' , blank=False )
    item_detail =models.TextField(max_length=255 , blank=True , null=True )
    likes = models.IntegerField(verbose_name='likes')
    discount_ammount = models.IntegerField(blank=True , null=True)
    price = models.IntegerField(default=0)
    gender = models.CharField(max_length=6,choices=Gender_Choice, default='Unisex')

    def __str__(self):
        return self.item_name
    
class Comment(models.Model):
    ItemListed = models.ForeignKey(ItemListed , on_delete=models.CASCADE)
    user_iden = models.CharField(max_length=150)
    comments = models.CharField(max_length=150)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return self.user_iden

class cart(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    item = models.ForeignKey(ItemListed , on_delete=models.CASCADE)
    quantity = models.IntegerField(null=True , default=0)
    
    def __str__(self):
        return str(self.item)

prac/app1/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import fields
from .models import UserProfile
class customform(UserCreationForm):
    class Meta:
        model = User
        fields = ['username' , 'email' , 'password1' ,'password2']


class settingform(forms.ModelForm):
    class Meta:
        model = User
        exclude =('password','is_staff','is_active','date_joined','last_login',"is_superuser",'user_permissions','groups')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude =('user','pic','valid_seller','company_name')

class picForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields=['pic']

prac/app1/views.py
from django.http import request
from django.http import response
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from .forms import customform, settingform ,UserProfileForm , picForm
from django.contrib.auth import authenticate , login
from django.contrib.auth.decorators import login_required
from .models import UserProfile,Comment
from .models import ItemListed
from django.contrib.auth.models import User
from django.core import serializers
from .models import UserProfile , cart

def create_user(request):
    torm = customform()
    if request.method =='POST':
        torm = customform(request.POST)
        if torm.is_valid():
            torm.save()
            user = User.objects.get(username = request.POST['username'])
            dorm = UserProfile(user = user)
            dorm.save()
            return redirect('/login/')
    
    ctx = {'form':torm}
    return render(request , 'app1/signup.html',ctx)
# Create your views here.
def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username , password = password)
        if user is not None:
            login(request ,user)
            return redirect('/home/')
    return render(request , 'app1/login.html')

@login_required(login_url='/login/')
def home(request):
    data = ItemListed.objects.all()
    currentuser = request.user
    cart_count = cart.objects.filter(user=request.user).count()
    ctx = {
        'user':currentuser,
        'UserProfile':UserProfile,
        'item':data,
        'cart_count':cart_count
    }
    return render(request, 'app1/home.html',ctx)

@login_required(login_url='/login/')
def setting_view(request):
    torm = settingform()
    dorm = UserProfileForm()
    pic = picForm()
    if request.method == 'POST':
        torm = settingform(request.POST , instance=request.user)
        if torm.is_valid():
            torm.save()
    
    userdata = User.objects.get(pk = request.user.id)
    ctx = {
            'setting':torm,
            'userdata':userdata,
            'userprofile':dorm,
            'pic':pic,
        }
    return render(request , 'app1/setting.html',ctx)

@login_required(login_url='/login/')
def general(request):
    data = {
        'xml':'Poka Radi'
    }
    return JsonResponse(data)


@login_required(login_url='/login/')
def usersentdata(request):
    if request.method=='POST':
        data = UserProfileForm(request.POST,instance=request.user.userprofile)
        if data.is_valid():
            data.save()
            redirect('/setting/')
        
    return redirect('/setting/')

@login_required(login_url='/login/')
def passwordvalidation(request):
    if request.method =="POST":
        user = User.objects.get(id = request.user.id)
        pwd1 = request.POST['password1']
        pwd2 = request.POST['password2']
        if pwd1 == pwd2:
            user.set_password(pwd1)
            user.save()
    return redirect('/setting/')

@login_required(login_url='/login/')
def addtocart(request):
    if request.method == 'GET':
        data = request.GET['data']
        cart_item = ItemListed.objects.get(id=data)
        try:
            cart_data = cart.objects.get(user=request.user , item = cart_item)
            cart_data.quantity = cart_data.quantity +1
            cart_data.save()
            length = cart.objects.filter(user=request.user).count()
            return JsonResponse(length , safe=False)
        except:
            cart_data = cart(user=request.user , item = cart_item , quantity = 1)
            cart_data.save()
            length = cart.objects.filter(user=request.user).count()
            return JsonResponse(length , safe=False)
    else:
        return JsonResponse('unsuccessful',safe=False)
    

@login_required(login_url='/login/')
def cartshow(request):
    cart_data = cart.objects.filter(user = request.user)
    ctx = {
        'data':cart_data,
    }
    return render(request , 'app1/cart.html',ctx)

@login_required(login_url='/login/')
def qntcng(request):
    if request.method=="GET":
        data = request.GET['data']
        idofdata = request.GET['id']
        ItemObject = ItemListed.objects.get(id=idofdata)
        cart_item = cart.objects.get(user=request.user ,item=ItemObject )
        if data == '-':
            if cart_item.quantity <= 1:
                cart_item.delete()
                return JsonResponse('delete', safe=False)
            else:
                cart_item.quantity -= 1
                cart_item.save()
                return JsonResponse(cart_item.quantity ,safe=False)
        elif data =='+':
            cart_item.quantity +=1
            cart_item.save()
            return JsonResponse(cart_item.quantity ,safe=False)
            

@login_required(login_url='/login/')
def bigpicview(request, id):
    Item_view = ItemListed.objects.get(id=id)
    cart_item = cart.objects.filter(user=request.user).count()
    print(cart_item)
    ctx = {
        'items':Item_view,
        'num':cart_item,
    }
    return render(request , 'app1/bigview.html' ,ctx)

@login_required(login_url='/login/')
def imagechange(request):
    if request.method == "GET":
        changepic = picForm(request.GET , request.FILES , instance=request.user)
        if changepic.is_valid():
            changepic.save()
        else:
            print('hi')
        return redirect('/setting/')
    

prac/app1/templates/app1/home.html
{% extends 'app1/base.html'%}
{% block content %}
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
  <div class="container-fluid">
      <a href="#" class="navbar-brand">
        <img src="{% static '/image/logo.png' %}" width="35" height="35" alt="img">
      </a>
      <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
          <div class="navbar-nav">
              <a href="/home/" class="nav-item nav-link active text-center text-light rounded mt-1 ml-1">Home</a>
              <a href="/setting/" class="nav-item nav-link text-center text-light rounded mt-1 ml-1">Profile</a>
              <div class="nav-item dropdown">
                  <a href="#" class="nav-link dropdown-toggle text-center text-light rounded mt-1 ml-1" data-bs-toggle="dropdown">Your Store</a>
                  <div class="dropdown-menu">
                      <a href="#" class="dropdown-item">Add New Item</a>
                      <a href="#" class="dropdown-item">Delete Existing Item</a>
                      <a href="#" class="dropdown-item">View Item</a>
                  </div>
              </div>
          </div>
        {% if request.user.is_authenticated %}
          <div class="navbar-nav dropdown">
            <a href="#" class="nav-item nav-link dropdown-toggle" data-bs-toggle="dropdown">
              <img src="{{request.user.userprofile.pic.url}}" alt="" width="45px" height="45px" class="rounded-circle">
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              <a href="#" class='dropdown-item'><img src="{{request.user.userprofile.pic.url}}" alt="" width="70px" height="70px" class="rounded-circle mx-5"></a>
              <a href="#" class='dropdown-item text-center'>@{{request.user.username}}</a>
              <div class="dropdown-divider"></div>
              <h6 class="dropdown-header">User History</h6>
              <a href="{% url 'app1:cart'%}" class="dropdown-item">Cart</a>
              <a href="#" class="dropdown-item">Wish List</a>
              <a href="#" class="dropdown-item">Inspection</a>
              <div class="dropdown-divider"></div>
              <h6 class="dropdown-header">Setting</h6>
              <a href="{% url 'app1:setting'%}" class="dropdown-item">Profile Setting</a>
              <a href="#" class="dropdown-item">Privacy & Policy</a>
              <a href="#" class="dropdown-item">User Store</a>
              <div class="dropdown-divider"></div>
              <a href="{% url 'app1:logout' %}" class="dropdown-item">Logout</a>
          </div>
          </div>
        {%else%}
          <div class="navbar-nav">
              <a href="{% url 'app1:login'%}" class="nav-item nav-link">Login</a>
          </div>
        {%endif%}
      </div>
  </div>
</nav>


<!--  Body starts from here ! -->




<div class="container-fluid mt-5">
  <div class="row">


    <!-- side bar for search-->

    <div class="col-sm-12 col-md-4 col-lg-2">
      <div class="container bg-light text-dark border rounded">
        <form action="" class="">
          <div class="header  mt-3"><h4>Filter</h4></div>
          <div class="row">
            <div class="col-12">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search">
                <button type="submit" class="btn btn-secondary"><i class="bi-search"></i></button>
            </div>
            </div>
          </div>
          <div class="row ml-3 mt-1">
            <h6 class="header">Gender</h6>
            <div class="col-12 ">
              <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                  <label class="form-check-label" for="flexCheckDefault">
                    Male
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="female">
                  <label class="form-check-label" for="female">
                    Female
                  </label>
                </div>
          </div>
          </div>
          <div class="row ml-3 mt-1">
            <h6 class="header">Size</h6>
            <div class="col-12 ">
              <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="Infant">
                  <label class="form-check-label" for="Infant">
                    Infant
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="Small">
                  <label class="form-check-label" for="Small">
                    Small
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="Medium">
                  <label class="form-check-label" for="Medium">
                    Medium
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="Large">
                  <label class="form-check-label" for="Large">
                    Large
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="XL">
                  <label class="form-check-label" for="XL">
                    Xl
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="XXL">
                  <label class="form-check-label" for="XXL">
                    XXl
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="XXXL">
                  <label class="form-check-label" for="XXXL">
                    XXXl
                  </label>
                </div>
          </div>
          </div>
          <div class="row ml-3 mt-1">
            <h6 class="header">Cloath Type</h6>
            <div class="col-12 ">
              <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="Innerwear">
                  <label class="form-check-label" for="Innerwear">
                    Innerwears
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="HeadWear">
                  <label class="form-check-label" for="HeadWear">
                    Head Wears
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="BodyWear">
                  <label class="form-check-label" for="BodyWear">
                    BodyWears
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="LegsWears">
                  <label class="form-check-label" for="LegsWears">
                    LeagsWears
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="FootWears">
                  <label class="form-check-label" for="FootWears">
                    FootWears
                  </label>
                </div>
          </div>
          </div>
        </form>
      </div>
    </div>


<!--  This is content ! -->



    <div class="col-sm-12 col-md-8 col-lg-8">
      <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active border-0 bg-primary mx-3" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" class="border-0 bg-primary mx-3" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" class="border-0 bg-primary mx-3" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static '/image/img1.jpg'%}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h5>@TheJeansFactory</h5>
              <p>The Fashion of new Generation</p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="{% static '/image/img2.jpg'%}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h5>Second slide label</h5>
              <p>Some representative placeholder content for the second slide.</p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="{% static '/image/img3.jpg'%}" class="d-block w-100 h-80" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h5>Third slide label</h5>
              <p>Some representative placeholder content for the third slide.</p>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev bg-transparent border-0" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next bg-transparent border-0" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
        <div class="row d-flex flex-row mt-5">
          {% for items in item%}
          <div class="col-lg-3 col-sm-4 col-md-4 mt-2">
            <div class="card mt-3 zoom" style="height: 500px; outline: 1px solid black; outline-offset: 5px;">
              <a href="{% url 'app1:bigview' items.id%}"><img src="{{items.pic.url}}" class="card-img-top" alt="..." height="250px" style="object-fit:cover"></a>
              <div class="card-body">
                <h5 class="card-title">{{items.item_name}}</h5>
                <p class="card-text bg-light"  >{{items.item_detail}}</p>
                <button class="border border-danger rounded bg-light" style="width: 100%; height: 40px;">${{items.price}}</button>
              </div>
              <div class="card-footer d-flex flex-row justify-content-between">
                <button class='rounded border bg-dark text-light' style='width:75px; height: 40px;'>Buy</button>
                <button class="rounded border bg-dark text-light addtocart" value="{{items.id}}" style="width: 150px;height: 40px;"><i class="bi bi-cart"></i>  Add To Cart</button>
              </div>
            </div>
          </div>
          {%endfor%}
        </div>
    </div>







    <div class="col-sm-12 col-md-12 col-lg-2">
      <div class="container bg-danger text-light">
        Here goes the ad staff
      </div>
    </div>
  </div>
</div>


<a href="/cart/"><div class="bg-danger rounded-circle text-center zoom" style="position: fixed; bottom: 5px; right: 5px; width: 50px;">
  <div style="position: absolute; width: 30px; height: 30px; font-weight: bold; right: -5px; top:-10px;" class="bg-dark text-white rounded-circle cart-count">{{cart_count}}</div>
  <i class="bi bi-cart" style="line-height: 50px;"></i>
  
</div></a>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src='{% static "/javascript/home.js"%}'></script>
{% endblock %}

prac/app1/templates/app1/setting.html
{% extends 'app1/base.html'%}
{% load static%}
{% block content%}
{% if setting %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
    <div class="container-fluid">
        <a href="#" class="navbar-brand">
          <img src="{% static '/image/logo.png' %}" width="35" height="35" alt="img">
        </a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
            <div class="navbar-nav">
                <a href="/home/" class="nav-item nav-link active text-center text-light rounded mt-1 ml-1">Home</a>
                <a href="/setting/" class="nav-item nav-link text-center text-light rounded mt-1 ml-1">Profile</a>
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle text-center text-light rounded mt-1 ml-1" data-bs-toggle="dropdown">Your Store</a>
                    <div class="dropdown-menu">
                        <a href="#" class="dropdown-item">Add New Item</a>
                        <a href="#" class="dropdown-item">Delete Existing Item</a>
                        <a href="#" class="dropdown-item">View Item</a>
                    </div>
                </div>
            </div>
          {% if request.user.is_authenticated %}
            <div class="navbar-nav dropdown">
              <a href="#" class="nav-item nav-link dropdown-toggle" data-bs-toggle="dropdown">
                <img src="{{request.user.userprofile.pic.url}}" alt="" width="45px" height="45px" class="rounded-circle">
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <a href="#" class='dropdown-item'><img src="{{request.user.userprofile.pic.url}}" alt="" width="70px" height="70px" class="rounded-circle mx-5"></a>
                <a href="#" class='dropdown-item text-center'>@{{request.user.username}}</a>
                <div class="dropdown-divider"></div>
                <h6 class="dropdown-header">User History</h6>
                <a href="#" class="dropdown-item">Cart</a>
                <a href="#" class="dropdown-item">Wish List</a>
                <a href="#" class="dropdown-item">Inspection</a>
                <div class="dropdown-divider"></div>
                <h6 class="dropdown-header">Setting</h6>
                <a href="{% url 'app1:setting'%}" class="dropdown-item">Profile Setting</a>
                <a href="#" class="dropdown-item">Privacy & Policy</a>
                <a href="#" class="dropdown-item">User Store</a>
                <div class="dropdown-divider"></div>
                <a href="{% url 'app1:logout' %}" class="dropdown-item">Logout</a>
            </div>
            </div>
          {%else%}
            <div class="navbar-nav">
                <a href="{% url 'app1:login'%}" class="nav-item nav-link">Login</a>
            </div>
          {%endif%}
        </div>
    </div>
  </nav>




<div class="container">
        {% csrf_token %}
        <div class="container-fluid d-flex flex-row jutstify-content-start mt-5 rounded" style="outline: 1px solid grey; outline-offset: 10px;">
            <img src="{{request.user.userprofile.pic.url}}" alt="img" width="150px" height="150px" class="rounded">
            <div class="container bg-light mx-3 rounded">
                <h3 class="header">@{{userdata.username}}</h3>
                <div class="container">
                    <small>{{request.user.userprofile.bio}}</small>
                </div>
            </div>
        </div>
        <div class="row mt-5">

            
            <div class="col-3">
                <div class="container-fluid">
                    <button style="width: 100%;height:40px;" class="rounded bg-dark border text-light" id='general'>General</button>
                    <button style="width: 100%;height:40px;" class="rounded bg-dark border text-light" id="usersetting">User Setting</button>
                    <button style="width: 100%;height:40px;" class="rounded bg-dark border text-light" id='profilepic'>Profile Pic</button>
                    <button style="width: 100%;height:40px;" class="rounded bg-dark border text-light" id='change_password'>Change Password</button>
                </div>
            </div>
            <div class="col-8 bg-light">
                <div class="container-fluid">
                    
                    <div class="container-fluid" id="general-view">
                        <h3 class="header">ABOUT</h3>
                    <div class="container">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, temporibus. Hic temporibus rem laborum non voluptas distinctio asperiores. Officiis atque pariatur recusandae vitae architecto, obcaecati quia mollitia quam tempore officia?</p>
                    </div>
                        <form action="" method="POST">
                            {%csrf_token%}
                            <div class="form-group">
                                <label for="id_username">Username:</label>
                                {{setting.username}}
                                <small class='text-danger'>{{setting.errors.username}}</small>
                            </div>
                            <div class="form-group">
                                <label for="id_first_name">First Name:</label>
                                {{setting.first_name}}
                                <small class='text-danger'>{{setting.errors.first_name}}</small>
                            </div>
                            <div class="form-group">
                                <label for="id_first_name">Last Name:</label>
                                {{setting.last_name}}
                                <small class='text-danger'>{{setting.errors.last_name}}</small>
                            </div>
                            <div class="form-group">
                                <label for="id_email">Email:</label>
                                {{setting.email}}
                                <small class='text-danger'>{{setting.errors.email}}</small>
                            </div>
                            <button type="submit" class="btn btn-default bg-dark text-light btn-block">Submit</button>
                            </form>
                    </div>
                    <div class="container-fluid" id="usersetting-view"> 
                        <form action="{% url 'app1:usersentdata'%}" method="POST">
                            {% csrf_token%}
                            <div class="form-group">
                                <label for="id_company_name">Bio</label>
                                {{userprofile.bio}}
                            </div>
                            <button type="submit" class="btn btn-default bg-dark text-light btn-block">Submit</button>
                        </form>
                    </div>
                    <div class="container-fluid" id="profilepic-view">
                        <form action="/profilepic/" method="GET" enctype="multipart/form-data">
                            <div class="form-group mt-3">
                            {{pic}}
                            <button type="submit" class="btn btn-block btn-primary mt-3">submit</button>
                            </div>
                        </form>
                    </div>
                    <div class="container-fluid" id="password-view">
                        <h3 class="header mt-5">Change Password</h3>
                        <div class="container">
                            <form action="/passvalidation/" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="id_password1">password</label>
                                    <input type="password" name="password1" id="id_password1" class="form-control validatepass">
                                </div>
                                <div class="form-group">
                                    <label for="id_password2">Re_password</label>
                                    <input type="password" name="password2" id="id_password2" class="form-control validatepass">
                                </div>
                                <button type="submit" class="btn btn-dark btn-block mb-5 submitpassword">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>



    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="{% static '/javascript/setting.js'%}"></script>
{% endif %}

{% endblock %}